### ISSUE TITLE
Turb doesn't turn off after laptop unplugged from power

### ISSUE THREAD

**Issue by KarkanAlzwayed** [Haptein/powerplan#1]
It worked just fine at work, but then I ran sudo `powerplan --daemon` then it stopped disabling turbo automatically after unplugging the power. I don't know for certain that that was the cause, but it just started happening after that. I don't know how to pull logs for this, but let me know what I'd need to do to help.
Thank
![Screenshot_20211008_222035](https://user-images.githubusercontent.com/49320606/136640684-feb0fbad-74b9-4d53-9f84-8820c5f37da3.png)
s

**Comment by Haptein** [comment]
Interesting... I think I know what could be causing this. Thanks 🤗

**Comment by Haptein** [comment]
I pushed a fix, let me know if this makes it behave correctly on your end ^^

**Comment by KarkanAlzwayed** [comment]
I am now getting this error when running `sudo powerplan --status`
```
kalzi@kalzi-NEON:~/powerplan$ sudo powerplan --status
Traceback (most recent call last):
  File "/usr/bin/powerplan", line 148, in <module>
    main_loop(monitor_mode)
  File "/usr/bin/powerplan", line 73, in main_loop
    profile.apply(charging_state)
TypeError: apply() takes 1 positional argument but 2 were given
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_opt_powerplan_src_powerplan.py.0.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/powerplan", line 148, in <module>
    main_loop(monitor_mode)
  File "/usr/bin/powerplan", line 73, in main_loop
    profile.apply(charging_state)
TypeError: apply() takes 1 positional argument but 2 were given

```

**Comment by Haptein** [comment]
This looks like a different, kind of unrelated issue. I can't reproduce this problem, but it seems (given your output) that the Linux interfaces needed to estimate power draw on your battery may disappear or become unavailable (for some time) after plugging and/or unplugging the power cord. I actually planned for some of these power supply related quirks (which are pretty common) but this is one I haven't encountered before.

Can you please monitor /sys/class/power_supply/BAT0/ while reproducing this problem? You can watch it's contents easily with:
```
watch -n 0.1 "grep . /sys/class/power_supply/BAT0/* -d skip"
```
Please share your output when it happens, my guess is that either current_now or voltage_now disappear for a bit.

**Comment by Haptein** [comment]
Hmm that's indeed some quirky behaviour. The OS itself is raising an error when trying to read from those two "files" (current_now and voltage_now) when you plug/unplug the power.

Does this happen every time you plug/unplug the power cord or does this seem a bit random at times?

**Comment by KarkanAlzwayed** [comment]
Ok, changed the polling rates to 4000 on both, and it is still happening. Plug-unplug-plug-unplug, then it happened. Second time was like plug-unplug, then it happened. BTW, I hope doing all of this doesn't hurt my hardware somehow, does it?

**Comment by KarkanAlzwayed** [comment]
>
If you just plug OR unplug it normally, the error doesn't come up, correct?
>
I don't know what you mean by that. I am just plugging-unplugging until it fails. That is all.

As for the rest of your comment. I don't really understand too much about the physics of computers and their power consumption, so I am not going to mess with those tdp values. Plus, I know for certain that my cpu does not support over/underclocking and undervolting. I have tried to do it before when I had windows running with an intel software that is made for this stuff, and it was telling me that my cpu isn't supported. Unless, you are talking about something else.

**Comment by Haptein** [comment]
I pushed a workaround. you can try it with:
```
git clone https://github.com/Haptein/powerplan.git -b PowerOSError
cd powerplan && sudo ./install
```

> I don't know what you mean by that. I am just plugging-unplugging until it fails. That is all.

I meant just plugging/unplugging and leaving it be.

> Plus, I know for certain that my cpu does not support over/underclocking and undervolting. I have tried to do it before when I had windows running with an intel software that is made for this stuff, and it was telling me that my cpu isn't supported. Unless, you are talking about something else.

I'm guessing you're talking about intel XTU, these TDP limits are called PL1 and PL2 there. Setting TDP limits isn't really undervolting/underclocking, it's basically telling your CPU to limit the amount of power it draws. If you feel like experimenting, you could watch the power your CPU package draws when under load and reasonably select a lower value. I can't really tell if your CPU has that option available, but that same infrastructure is what's used to report your CPU package power draw.

**Comment by KarkanAlzwayed** [comment]
> ```
> git clone https://github.com/Haptein/powerplan.git -b PowerOSError
> cd powerplan && sudo ./install
> ```
Tried that and it is still not working. I am not really too woried about, unless you want to continue to fix it.

As for the TDP values, what do you think I should set these to, based on my CPU:
```
ac_tdp_sustained = 0
ac_tdp_burst = 0
bat_tdp_sustained = 0
bat_tdp_burst = 0
```

**Comment by Haptein** [comment]
> As for the TDP values, what do you think I should set these to, based on my CPU

It depends on what you want to accomplish, but I think setting sustained/burst to 10/15 would work well for battery life. As for performance settings I've seen 30/45 being used with your CPU, but it depends on your laptop's cooling solution and if the manufacturer limits the CPU power draw on firmware.

**Comment by Surendrajat** [comment]
@Haptein I tried installing and getting similar error on `powerplan -s`:
```log
$ sudo powerplan -s
Traceback (most recent call last):
  File "/usr/bin/powerplan", line 148, in <module>
    main_loop(monitor_mode)
  File "/usr/bin/powerplan", line 77, in main_loop
    status.show_system_status(profile, monitor_mode)
  File "/opt/powerplan/src/status.py", line 38, in show_system_status
    power_status = f'Charging: {powersupply.charging()}\t\tBattery draw: {powersupply.power_draw():.1f}W'
  File "/opt/powerplan/src/powersupply.py", line 101, in power_draw
    return read(POWER_NOW, int) / 10**6
  File "/opt/powerplan/src/shell.py", line 15, in read
    data = file.readline().strip()
OSError: [Errno 19] No such device
```

**Comment by KarkanAlzwayed** [comment]
> I'm willing as long as you are ^^. It must have thrown a distinct error this time, since OSError was specifically added as possible/expected behaviour.
> 
It's fine with me, but we will have to continue tomorrow or later this week, as I'm going back to work tomorrow. 

> It depends on what you want to accomplish, but I think setting sustained/burst to 10/15 would work well for battery life. As for performance settings I've seen 30/45 being used with your CPU, but it depends on your laptop's cooling solution and if the manufacturer limits the CPU power draw on firmware.
>
Are they literally written this way 10/15, 30/45, or are you just giving me a range, and I should write them as numbers like 10 or 15?

**Comment by Haptein** [comment]
@Surendrajat unless you also have the same computer I think this must be too much of a coincidence. I will have to look more carefully into it... Could I bother you with the output of:
```
sudo powerplan --system
```

@KarkanAlzwayed It should be something like this:
bat_tdp_sustained = 10
bat_tdp_burst = 16

tdp_sustained is PL1 and tdp_burst is PL2.

**Comment by Surendrajat** [comment]
@Haptein maybe I do :)
Here you go:
```log
    System
    OS:			Linux-5.14.9-200.fc34.x86_64-x86_64-with-glibc2.33
    powerplan:		0.7.1 running on Python3.9.7 with psutil5.8.0
    CPU model:		11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Core configuraton:	4/8  0-4 1-5 2-6 3-7
    Frequency range:	400000 - 2400000 - 4200000
    Driver:		intel_pstate
    Turbo:		/sys/devices/system/cpu/intel_pstate/no_turbo
    Governors:		performance, powersave
    Policies:		default, performance, balance_performance, balance_power, power
    Temperature:	acpitz, nvme, *coretemp, iwlwifi_1
    AC adapter:		ADP1
    Battery:		BAT0
    Power method:	power
```

**Comment by Haptein** [comment]
@KarkanAlzwayed  @Surendrajat I checked the Kernel's source code and it seems it indeed raises errno 19 (ENODEV) when battery values are unknown. I added an except for this specific case.

You can try it with this specific branch:
```
git clone https://github.com/Haptein/powerplan.git -b PowerOSError
cd powerplan && sudo ./install
```

**Comment by Haptein** [comment]
@Surendrajat Thanks! I wanted to corroborate this being fixed as I can't replicate it myself.

> Though Battery draw is always -1.0W for me.

Unfortunately, what that means is that the kernel can't read the battery value within the acpi battery driver. You can corroborate this trying this:
```
grep . /sys/class/power_supply/BAT0/* -d skip
```
If your battery also supports the other method of computing power draw (I haven't seen one supporting both yet) then it'd be worth implementing the needed checks for that.

I was thinking of printing something like a dash symbol there if values like these are unknown. What do you think?

**Comment by KarkanAlzwayed** [comment]
Looks like I have missed a lot. I've been crazy busy with work. I have tried this last command `git clone https://github.com/Haptein/powerplan.git -b PowerOSError`, but it complains that the `powerplan` directory already exists, so, I just did a `git pull` on the old one I already had, assuming that you have merged all the fixes that I've missed, and it is working fine now. I am also thinking of mentioning this repo to the KDE plasma devs to see if they'd like to take a look at it. I know they are already including `power-profiles-daemon` in kde 5.23, but in my experience, this solution has been giving me much better results.

**Comment by KarkanAlzwayed** [comment]
Is this something you'll need to maintain and keep up to date, or is it just one thing and then done? I'm asking because I want to know if I should `git pull` every now and then to get the latest update. Thanks.

**Comment by Haptein** [comment]
This program interfaces directly with tools provided by the Linux kernel. As such maintainment depends on changes in the Kernel itself. The interfaces used here have been around for a while now and seem pretty stable, so If it works right now for your machine I wouldn't worry too much.

On the other hand, new stuff also comes out all the time, particularly lately. Support for new frequency scaling drivers for example will have to be added when they get released. There's also a couple of features planned (that afaik aren't available elsewhere). So it might be worth updating every now and then.

**Comment by KarkanAlzwayed** [comment]
Ah, makes sense. Thank you. Any plans on making a GUI app for this (Qt would be great)? I am tempted to try to make one, but I know it would probably take me at least a year to make one, since I don't know much about programming and don't have enough time to work on it.

**Comment by Haptein** [comment]
@KarkanAlzwayed Let's continue this discussion here #3  :)
